"""tables definitions

Revision ID: 252f1806d9eb
Revises: 54e2fb61157d
Create Date: 2025-05-04 14:59:33.813010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '252f1806d9eb'
down_revision: Union[str, None] = '54e2fb61157d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_schema_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('comment', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['table_schema_id'], ['table_schemas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_schema_id', 'name', name='uq_table_definitions')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('table_definitions')
    # ### end Alembic commands ###
