"""user groups member uniq

Revision ID: bfb5ee843884
Revises: ff16ad01c2cc
Create Date: 2025-04-23 20:53:17.085577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfb5ee843884'
down_revision: Union[str, None] = 'ff16ad01c2cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_group_membership', 'user_group_membership', ['user_id', 'group_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_group_membership', 'user_group_membership', type_='unique')
    # ### end Alembic commands ###
